### ISSUE TITLE
After resize event?

### ISSUE THREAD

**Issue by uitlaber** [Fuxy526/vue-columns-resizable#1]
Can i listen after resize event?

**Comment by ligne13** [comment]
Hi,

have you found something ?
I would like to get the size of every column after resize. Does the library return the values ? or do I have  to calculate them myself with JS ?

thanks !

**Comment by uitlaber** [comment]
Hi, @ligne13 !
Not found ,  try mousemove event and calculate columns.

**Comment by yanko-belov** [comment]
This is a valid issue. An event with the columns widths will be very useful.
